version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  site:
    image: node:latest
    container_name: site
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install && npm run seed & npm run start "
    depends_on:
      - mongodb
    env_file:
      - ./.env
  
  frontend:
    image: node:latest
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install && npm run start"

volumes:
  mongodb_data: